### ISSUE TITLE
Insecure storage mechanism.

### ISSUE THREAD

**Issue by codeswhite** [YonLiud/Nudle#1]
Please consider implementing an encryption or even an encoding, rather than storin the sensitive information in plain text.
https://github.com/YonLiud/Nudle/blob/beaa0b865638b413f74b9145903199e1d3654081/VimPas.cpp#L11-L13

**Comment by YonLiud** [comment]
are u serious!? it's **THE BEST** security possible!

(seriously now, I didn't plan on actually working on this project, more of a welcome project to C++, from 2 years ago

**Comment by codeswhite** [comment]
Practice makes perfection
